Improve the code of calculating the optimal `TextInputValidationResult`.
artyom-stv/TextInputKit pull request #19
Opened 2016-12-20 20:51 UTC by artyom-stv

2016-12-22 10:28 UTC, Vladlex reviewed
Please, answer the question about rejecting

2016-12-22 10:28 UTC, Vladlex commented on TextInputKit/TextInputKit/Code/TextInputFormatter/TextInputValidationResult+OptimizeChanges.swift
> +        let shouldReject: Bool = {
Do we reject if we have no changes?

2016-12-22 10:42 UTC, artyom-stv commented on TextInputKit/TextInputKit/Code/TextInputFormatter/TextInputValidationResult+OptimizeChanges.swift
> +        let shouldReject: Bool = {
Yes.

So, if we imagine a pipeline of text input events, we can prevent calls to the event handlers in advance.

2016-12-27 13:37 UTC, Vladlex requested changes

2016-12-27 13:37 UTC, Vladlex commented on TextInputKit/TextInputKit/Code/TextInputFormatter/TextInputValidationResult+OptimizeChanges.swift
> +        let shouldReject: Bool = {
I would rather name variable is 'hasNoChanges' and reject if it's true.
It will describe sense of expression better

2016-12-27 13:59 UTC, Vladlex approved these changes

2016-12-27 15:33 UTC, merged